Repository tablecheck/tablekit, pull requests merged in 2021-08, with the labels that each got.

#6 fix: storybook icon config
  .storybook/preview.tsx
  packages/avatar/src/Avatar.stories.mdx
  packages/footer/src/Footer.stories.mdx
  packages/gallery/src/Gallery.stories.mdx
  packages/language-selector/src/LanguageSelector.stories.tsx
  packages/password-field/src/PasswordField.stories.mdx
  packages/sidenav/src/Sidenav.stories.mdx
  packages/tag/src/Tag.stories.mdx
  packages/toggle/src/Toggle.stories.mdx
Labels: internal, skip-release

#19 chore: fix all contributors setup [skip-ci]
  .all-contributorsrc
  .autorc
  README.md
Labels: internal

#22 fix(tablekit-phone-input): update dependencies
  package-lock.json
  package.json
  packages/phone-input/package.json
Labels: patch, dependencies, phone-input

#28 fix: remove some packages that use react-spring
  auditjs.json
  package-lock.json
  package.json
  packages/footer/CHANGELOG.md
  packages/footer/HISTORY.md
  packages/footer/LICENSE
  packages/footer/package.json
  packages/footer/src/Footer.md
  packages/footer/src/Footer.stories.mdx
  packages/footer/src/Footer.tsx
  packages/footer/src/__tests__/index.tsx
  packages/footer/src/components/ContentRow/ActionButtons.tsx
  packages/footer/src/components/ContentRow/NavigationLists.tsx
  packages/footer/src/components/ContentRow/SocialLinks.tsx
  packages/footer/src/components/ContentRow/styled.ts
  packages/footer/src/components/FooterRow/index.tsx
  packages/footer/src/components/FooterRow/styled.ts
  packages/footer/src/demoContent.ts
  packages/footer/src/index.ts
  packages/footer/src/styled.ts
  packages/footer/src/themes.ts
  packages/footer/src/types.ts
  packages/gallery/CHANGELOG.md
  packages/gallery/HISTORY.md
  packages/gallery/LICENSE
  packages/gallery/package.json
  packages/gallery/src/Gallery.md
  packages/gallery/src/Gallery.stories.mdx
  packages/gallery/src/Gallery.tsx
  packages/gallery/src/__tests__/index.tsx
  packages/gallery/src/index.ts
  packages/gallery/src/styled.ts
  packages/gallery/src/themes.ts
  packages/gallery/src/types.ts
  packages/language-selector/package.json
  packages/package-namespace/src/PackageNamespace.ts
  packages/spinner/package.json
  packages/spinner/src/Spinner.stories.tsx
  packages/spinner/src/Spinner.tsx
  packages/spinner/src/__tests__/index.tsx
  packages/spinner/src/components/SpinnerSvg.ts
  packages/spinner/src/components/styledContainer.ts
  packages/tag/package.json
Labels: internal, dependencies

#34 chore: setup temporary release process
  .autorc
  .github/workflows/label_checker.yml
  .github/workflows/pull_requests.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: skip-release

#32 fix(tablekit-input-button): changed appearance
  packages/input-button/src/__snapshots__/index.test.tsx.snap
  packages/input-button/src/styled.ts
Labels: patch

#33 feat(tablekit-modal-dialog): add maxWidth and maxHeight props
  packages/modal-dialog/package.json
  packages/modal-dialog/src/ModalDialog.stories.tsx
  packages/modal-dialog/src/ModalDialog.tsx
  packages/modal-dialog/src/components/AnimatedContent.tsx
  packages/modal-dialog/src/styled.ts
  packages/modal-dialog/src/types.ts
Labels: enhancement, patch

#37 chore: migrate approved stories 
  .storybook/preview.tsx
  packages/alert/package.json
  packages/alert/src/Alert.stories.mdx
  packages/alert/src/Alert.stories.tsx
  packages/avatar/package.json
  packages/avatar/src/Avatar.stories.mdx
  packages/avatar/src/Avatar.stories.tsx
  packages/badge/package.json
  packages/badge/src/Badge.stories.mdx
  packages/badge/src/Badge.stories.tsx
  packages/checkbox/package.json
  packages/checkbox/src/Checkbox.stories.tsx
  packages/icon/package.json
  packages/icon/src/Icon.stories.mdx
  packages/icon/src/Icon.stories.tsx
  packages/input-button/package.json
  packages/input-button/src/InputButton.stories.mdx
  packages/input-button/src/InputButton.stories.tsx
  packages/input/package.json
  packages/input/src/Input.stories.mdx
  packages/input/src/Input.stories.tsx
  packages/logo/package.json
  packages/logo/src/Logo.stories.tsx
  packages/radio/package.json
  packages/radio/src/Radio.stories.tsx
  packages/select/package.json
  packages/select/src/Select.stories.mdx
  packages/select/src/Select.stories.tsx
  packages/table/package.json
  packages/table/src/Table.stories.tsx
  packages/table/src/docUtils.ts
  packages/tag/src/Tag.stories.mdx
  packages/toggle/package.json
  packages/toggle/src/Toggle.stories.mdx
  packages/toggle/src/Toggle.stories.tsx
  packages/tooltip/package.json
  packages/tooltip/src/Tooltop.stories.tsx
Labels: internal, released

#24 build: add possibility to load from assets
  package.json
Labels: internal

#29 docs: intro page
  pages/Intro/Intro.stories.mdx
Labels: internal

#36 docs: migrate unapproved stories
  .storybook/main.js
  packages/banner/package.json
  packages/banner/src/Banner.stories.tsx
  packages/button-group/package.json
  packages/button-group/src/ButtonGroup.stories.tsx
  packages/button/package.json
  packages/button/src/stories/Button.stories.tsx
  packages/button/src/stories/storyStyles.ts
  packages/button/src/stories/storyTemplates.tsx
  packages/calendar/package.json
  packages/calendar/src/Calendar.stories.mdx
  packages/calendar/src/Calendar.stories.tsx
  packages/calendar/src/Months/Month.stories.tsx
  packages/calendar/src/Months/Months.stories.mdx
  packages/calendar/src/Weeks/Week.stories.mdx
  packages/calendar/src/Weeks/Week.stories.tsx
  packages/calendar/src/Weeks/WeekHeader.stories.mdx
  packages/calendar/src/Weeks/WeekHeader.stories.tsx
  packages/calendar/src/storyStyles.ts
  packages/inline-dialog/package.json
  packages/inline-dialog/src/InlineDialog.stories.tsx
  packages/item/package.json
  packages/item/src/Item.stories.tsx
  packages/item/src/ItemGroup.stories.tsx
  packages/modal-dialog/package.json
  packages/modal-dialog/src/Modal.stories.mdx
  packages/panel/package.json
  packages/panel/src/Panel.stories.mdx
  packages/panel/src/Panel.stories.tsx
  packages/panel/src/ResizablePanel.stories.mdx
  packages/panel/src/ResizablePanel.stories.tsx
  packages/password-field/package.json
  packages/password-field/src/PasswordField.stories.mdx
  packages/password-field/src/PasswordField.stories.tsx
  packages/password-field/src/PasswordField.tsx
  packages/phone-input/src/PhoneInput.stories.mdx
  packages/sidenav/src/Sidenav.stories.mdx
  packages/tabs/package.json
  packages/tabs/src/Tabs.stories.tsx
  packages/textarea/package.json
  packages/textarea/src/Textarea.stories.mdx
  packages/textarea/src/Textarea.stories.tsx
  packages/topnav/package.json
  packages/topnav/src/stories/TopNav.stories.tsx
  packages/topnav/src/stories/storyStyles.ts
Labels: documentation

#48 fix(icon): improve icon config error
  packages/icon/src/utils.ts
Labels: patch
