Repository tablecheck/tablekit, pull requests merged in 2022-01, with the labels that each got.

#77 fix(tablekit-password-field): wrong invalid appearance
  packages/password-field/src/PasswordFieldStateless.tsx
  packages/password-field/src/utils.ts
Labels: patch, password-input

#82 security(tablekit-icon): colors.js has embedded denial of service
  packages/icon/package.json
Labels: dependencies

#83 security: update dependencies
  createNewPackage.js
  package-lock.json
  package.json
  packages/alert/package.json
  packages/avatar/package.json
  packages/avatar/src/__tests__/__snapshots__/index.test.tsx.snap
  packages/badge/package.json
  packages/badge/src/__tests__/__snapshots__/index.test.tsx.snap
  packages/banner/package.json
  packages/banner/src/__tests__/__snapshots__/index.tsx.snap
  packages/button-group/package.json
  packages/button/package.json
  packages/button/src/Button.tsx
  packages/calendar/package.json
  packages/checkbox/package.json
  packages/inline-dialog/package.json
  packages/inline-dialog/src/__tests__/__snapshots__/index.tsx.snap
  packages/input-button/package.json
  packages/input-button/src/__snapshots__/index.test.tsx.snap
  packages/input/package.json
  packages/item/package.json
  packages/item/src/Item.stories.tsx
  packages/item/src/__snapshots__/index.test.tsx.snap
  packages/language-selector/package.json
  packages/logo/package.json
  packages/logo/src/__snapshots__/index.test.tsx.snap
  packages/modal-dialog/package.json
  packages/package-namespace/package.json
  packages/panel/package.json
  packages/panel/src/__tests__/__snapshots__/index.test.tsx.snap
  packages/password-field/package.json
  packages/password-field/src/types.ts
  packages/phone-input/package.json
  packages/radio/package.json
  packages/select/package.json
  packages/select/src/createSelect.tsx
  packages/sidenav/src/__tests__/__snapshots__/index.tsx.snap
  packages/spinner/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/tabs/src/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/tag/package.json
  packages/tag/src/__tests__/__snapshots__/index.tsx.snap
  packages/textarea/package.json
  packages/toggle/package.json
  packages/tooltip/package.json
  packages/tooltip/src/__tests__/__snapshots__/index.tsx.snap
  packages/topnav/package.json
  packages/utils/src/mediaQuery.ts
  packages/utils/src/spacing.ts
Labels: dependencies

#84 feat(tablekit-sidenav): support carbon icons in sidenav
  package-lock.json
  package.json
  packages/sidenav/package.json
  packages/sidenav/src/Sidenav.md
  packages/sidenav/src/components/NavItem.tsx
  packages/sidenav/src/components/NavSection.tsx
  packages/sidenav/src/examples/navItems.tsx
  packages/sidenav/src/stories/Sidenav.stories.tsx
  packages/sidenav/src/stories/storyStyles.ts
  packages/sidenav/src/types.ts
Labels: minor

#59 docs: migrate Iconography
  packages/free-icon-config/package.json
  packages/icon/package.json
  packages/icon/src/Icon.stories.tsx
  packages/icon/src/Iconography.stories.tsx
  packages/topnav/package.json
Labels: documentation

#47 docs: create stories for UI Helpers
  packages/theme/package.json
  packages/theme/src/Theme.stories.tsx
  packages/theme/src/ThemeProvider.stories.tsx
  packages/typography/package.json
  packages/typography/src/Link.stories.tsx
  packages/typography/src/Typography.stories.tsx
  packages/utils/package.json
  packages/utils/src/Utils.stories.tsx
  packages/utils/src/storyTemplate.tsx
Labels: documentation

#85 fix(tablekit-input): change font size to 16px
  packages/input/src/styled/index.ts
Labels: patch, input

#86 fix(tablekit-password-field): export stateless version
  packages/password-field/src/index.ts
Labels: patch, password-input
