Repository tablecheck/tablekit, pull requests merged in 2022-11, with the labels that each got.

#142 chore: fix auditjs
  auditjs.json
  package-lock.json
  package.json
Labels: dependencies

#129 feat(tablekit-react): add toggle component
  system/react/src/components/Toggle.stories.tsx
  system/react/src/components/Toggle.ts
  system/react/src/index.ts
Labels: minor, toggle

#145 feat: update react select config
  system/react-select/src/index.tsx
Labels: patch

#147 fix(tablekit-react): hardcode values for interop with IDE extensions
  system/react/src/themeVariables/constants.ts
Labels: patch

#146 fix: fix input, button and focus styles
  system/react/src/components/Button.ts
  system/react/src/components/Buttons.stories.tsx
  system/react/src/components/Input.ts
  system/react/src/components/InputLikeButton.stories.tsx
  system/react/src/components/InputLikeButton.ts
  system/react/src/components/Inputs.stories.tsx
  system/react/src/components/Select.ts
Labels: patch

#149 fix: update selected button group item styles
  system/react/src/components/ButtonGroup.ts
Labels: patch
