Repository tablecheck/tablekit, pull requests merged in 2023-08, with the labels that each got.

#196 feat(tablekit-core): add `data-variant` as prop for `MenuItem`
  system/core/src/components/MenuItem.ts
  system/stories/src/Menu.stories.tsx
Labels: enhancement, minor

#197 fix: make button and icon button consistently sized
  system/core/src/components/Button.ts
  system/core/src/components/IconButton.ts
Labels: patch

#198 fix: add wrap option to tabs and reduce gap to 8px
  system/core/src/components/Tabs.ts
Labels: patch

#201 feat: add default anchor styling
  system/core/src/components/MenuItem.ts
  system/core/src/utils/resetCss.ts
  system/stories/src/Menu.stories.tsx
Labels: minor

#202 fix: link hover/active/visited only apply when link
  system/core/src/components/Button.ts
  system/core/src/components/IconButton.ts
  system/core/src/components/MenuItem.ts
  system/core/src/utils/resetCss.ts
  system/stories/src/Menu.stories.tsx
Labels: patch

#203 fix: move link to Anchor component
  system/.eslintrc.js
  system/core/src/components/Anchor.ts
  system/core/src/index.ts
  system/core/src/utils/resetCss.ts
  system/react-css/scripts/generateComponents.mjs
  system/react-css/src/components/Anchor.tsx
  system/react-css/src/index.ts
  system/react/scripts/generateComponents.mjs
  system/react/src/components/Anchor.tsx
  system/react/src/index.ts
  system/stories/src/Anchor.stories.tsx
Labels: patch

#204 feat: add component to auto apply anchor styling to children
  system/core/src/components/ChildAnchors.ts
  system/core/src/index.ts
  system/react-css/src/components/ChildAnchors.tsx
  system/react-css/src/index.ts
  system/react/src/components/ChildAnchors.tsx
  system/react/src/index.ts
  system/stories/src/ChildAnchors.stories.tsx
Labels: minor
