Repository tablecheck/tablekit, pull requests merged in 2023-06, with the labels that each got.

#186 feat(tablekit-core): change color for error in `InputAlert`, add stories for `InputStructure` and `InputAlert`
  system/core/src/components/InputAlert.ts
  system/react/src/index.ts
  system/react/src/structuredComponents/InputStructure.tsx
  system/stories/src/InputAlert.stories.tsx
  system/stories/src/InputStructure.stories.tsx
Labels: bug, documentation

#187 fix(tablekit-core): update warn text for `InputAlert`
  system/core/src/components/InputAlert.ts
Labels: bug, patch

#188 fix: correct scoping for allFiles to pass to minifier
  system/css/src/build.ts
Labels: patch
